export const PathName = {
    HOME: "/",
    LOGIN: "/login",
    TRANSACTION: "transactions",
    HISTORY: "historys",
    SETTING: "settings",
    ORTHER: "orther",
    SYMMETRICAL_ORDER: "symmetrical-order",
    NOTIFICATION: "notification",
    INFOACC: "info_acc",
    ACCMONITOR: "acc_monitor",
    ACCTRANSACTION: "acc_transaction",
    EMAIL: "email",
    LANGUAGE: "language",
    TRANSACTION_BOOT: "transactions_boot",
    MONITOR_ACC_BOOT: "monitor_acc_boot",
    MONITOR_BOOT: "monitor_boot",
    TRANSACTION_ACC_MONITOR_BOOT: "transaction_acc_monitor_boot",
    NOTIFICATION_DETAIL: (id?: number) => `/settings/notification/${id ?? ':id'}`,
    BOOT_ORDER_DETAIL: (id?: number) => `/symmetrical-order/monitor_boot/${id ?? ':id'}`,
    BOOT_ACC_ORDER_DETAIL: (id?: number) => `/symmetrical-order/monitor_acc_boot/${id ?? ':id'}`,
}