export const PathName = {
    HOME: "/",
    LOGIN: "/login",
    TRANSACTION: "transactions",
    HISTORY: "historys",
    SETTING: "settings",
    ORTHER: "orther",
    SYMMETRICAL_ORDER: "symmetrical-order",
    NOTIFICATION: "notification",
    INFOACC: "info_acc",
    ACCMONITOR: "acc_monitor",
    ACCTRANSACTION: "acc_transaction",
    EMAIL: "email",
    LANGUAGE: "language",
    NOTIFICATION_DETAIL: (id?: number) => `/settings/notification/${id ?? ':id'}`,
}